os:
  - trusty

language: node_js
node_js:
  - "7"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install -g npm@4.6.1
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

script:
  - npm run build:prod
  - find .
