language: node_js
node_js:
  - "7"

os:
  - osx
  - linux

dist: precise

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install -g npm@4.6.1
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

script:
  - npm run check-prettiness
  - npm run lint
  - npm run build:prod
  - npm run test:setup
  - npm test

after_success:
  - npm run publish

after_failure:
  - npm run test:review

#branches:
#  only:
#    - master
#    - /^__release-.*/

notifications:
  email:
    on_success: never
    on_failure: change
